# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('zendesk_group_id', models.CharField(max_length=100)),
            ],
        ),
    ]
