# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20161210_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
