# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='group',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='private_comment',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='stage',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='vertical',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='zendesk_ticket_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
