# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20161210_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vertical',
        ),
    ]
