# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20161213_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assignee_id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.Agent'),
        ),
    ]
