# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20161213_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('question', 'Question'), ('incident', 'Incident'), ('problem', 'Problem'), ('task', 'Task')], max_length=50),
        ),
    ]
