# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20161214_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], max_length=50),
        ),
    ]
