# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20161214_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_groups.AgentGroup'),
        ),
    ]
