# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20161214_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
