# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('tickets', '0013_auto_20161230_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
        ),
    ]
