# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='private_comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
