# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20161231_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
            preserve_default=False,
        ),
    ]
