# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20161231_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='private_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
