# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20170111_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='requester_id',
        ),
    ]
