# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-08-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_auto_20170131_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
