# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2018-06-11 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_ticket_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketzendeskapiusage',
            name='organization',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ticketzendeskapiusage',
            name='requester',
            field=models.EmailField(max_length=300, null=True),
        ),
    ]
