# Generated by Django 2.1.3 on 2019-07-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_auto_20181201_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cycle',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
