# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True),
        ),
    ]
