FROM python:3.6.0

RUN pip install Django==2.1.3 \
    django-admin-env-notice==0.1.5 \
    django-tables2==1.3.0 \
    flake8==3.3.0 \
    flake8-print==2.0.2 \
    psycopg2==2.7.1 \
    requests==2.20.1 \
    pytest-django==3.4.3

ENV APPLICATION_ROOT /app/

RUN mkdir $APPLICATION_ROOT
COPY . $APPLICATION_ROOT
COPY ./compose/django/entrypoint-local.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
WORKDIR $APPLICATION_ROOT

RUN pip install -r requirements/local.txt
