from django.test import TestCase

from ..models import Board, BoardGroup


class BoardTest(TestCase):
    def test_save_board(self):
        board = Board()
        board.name = 'Pre-Production'
        board.slug = 'pre-production'
        board.save()

        board = Board.objects.last()

        self.assertEqual(board.name, 'Pre-Production')
        self.assertEqual(board.slug, 'pre-production')

    def test_board_should_represent_name_by_default(self):
        board = Board.objects.create(
            name='Pre-Production',
            slug='pre-production'
        )
        self.assertEquals(board.__str__(), 'Pre-Production')

    def test_slug_should_be_autogenerated_from_board_name(self):
        board = Board.objects.create(name='Pre-Production')

        self.assertEquals(board.slug, 'pre-production')

    def test_save_board_with_group(self):
        board = Board.objects.create(name='Pre-Production')

        board_group = BoardGroup.objects.create(name='CP Production')
        board.board_group = board_group
        board.save()

        board = Board.objects.last()

        self.assertEquals(board.board_group.name, 'CP Production')


class BoardGroupTest(TestCase):
    def test_save_board_group(self):
        board_group = BoardGroup()
        board_group.name = 'CP Production'
        board_group.save()

        board_group = BoardGroup.objects.last()

        self.assertEqual(board_group.name, 'CP Production')

    def test_board_group_should_represent_name_by_default(self):
        board_group = BoardGroup.objects.create(
            name='CP Production'
        )
        self.assertEquals(board_group.__str__(), 'CP Production')
