# Generated by Django 2.1.3 on 2018-12-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20170103_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boards.BoardGroup'),
        ),
    ]
